export const BGG_COLLECTION_LIST_REQUEST = 'BGG_COLLECTION_LIST_REQUEST'
export const BGG_COLLECTION_LIST_SUCCESS = 'BGG_COLLECTION_LIST_SUCCESS'
export const BGG_COLLECTION_LIST_FAIL = 'BGG_COLLECTION_LIST_FAIL'
export const BGG_COLLECTION_LIST_RESET = 'BGG_COLLECTION_LIST_RESET'

export const BGG_GAME_DETAILS_REQUEST = 'BGG_GAME_DETAILS_REQUEST'
export const BGG_GAME_DETAILS_SUCCESS = 'BGG_GAME_DETAILS_SUCCESS'
export const BGG_GAME_DETAILS_FAIL = 'BGG_GAME_DETAILS_FAIL'
