// const cities = [
// 	{ judet: 'Alba', nume: 'Aiud' },
// 	{ judet: 'Alba', nume: 'Blaj' },
// 	{ judet: 'Alba', nume: 'Cugir' },
// 	{ judet: 'Alba', nume: 'Sebes' },
// 	{ judet: 'Alba', nume: 'Alba Iulia' },
// 	{ judet: 'Arad', nume: 'Pecica' },
// 	{ judet: 'Arad', nume: 'Santana' },
// 	{ judet: 'Arad', nume: 'Arad' },
// 	{ judet: 'Arges', nume: 'Campulung' },
// 	{ judet: 'Arges', nume: 'Curtea de Arges' },
// 	{ judet: 'Arges', nume: 'Mioveni' },
// 	{ judet: 'Arges', nume: 'Pitesti' },
// 	{ judet: 'Bacau', nume: 'Buhusi' },
// 	{ judet: 'Bacau', nume: 'Comanesti' },
// 	{ judet: 'Bacau', nume: 'Moinesti' },
// 	{ judet: 'Bacau', nume: 'Bacau' },
// 	{ judet: 'Bacau', nume: 'Onesti' },
// 	{ judet: 'Bihor', nume: 'Beius' },
// 	{ judet: 'Bihor', nume: 'Marghita' },
// 	{ judet: 'Bihor', nume: 'Salonta' },
// 	{ judet: 'Bihor', nume: 'Oradea' },
// 	{ judet: 'Bistrita-Nasaud', nume: 'Bistrita' },
// 	{ judet: 'Botosani', nume: 'Dorohoi' },
// 	{ judet: 'Botosani', nume: 'Botosani' },
// 	{ judet: 'Braila', nume: 'Braila' },
// 	{ judet: 'Brasov', nume: 'Codlea' },
// 	{ judet: 'Brasov', nume: 'Fagaras' },
// 	{ judet: 'Brasov', nume: 'Rasnov' },
// 	{ judet: 'Brasov', nume: 'Rasnov Romacril' },
// 	{ judet: 'Brasov', nume: 'Sacele' },
// 	{ judet: 'Brasov', nume: 'Zarnesti' },
// 	{ judet: 'Brasov', nume: 'Brasov' },
// 	{ judet: 'Buzau', nume: 'Ramnicu Sarat' },
// 	{ judet: 'Buzau', nume: 'Buzau' },
// 	{ judet: 'Calarasi', nume: 'Oltenita' },
// 	{ judet: 'Calarasi', nume: 'Calarasi' },
// 	{ judet: 'Caras-Severin', nume: 'Bocsa' },
// 	{ judet: 'Caras-Severin', nume: 'Caransebes' },
// 	{ judet: 'Caras-Severin', nume: 'Resita' },
// 	{ judet: 'Cluj', nume: 'Campia Turzii' },
// 	{ judet: 'Cluj', nume: 'Dej' },
// 	{ judet: 'Cluj', nume: 'Gherla' },
// 	{ judet: 'Cluj', nume: 'Floresti' },
// 	{ judet: 'Cluj', nume: 'Cluj-Napoca' },
// 	{ judet: 'Cluj', nume: 'Turda' },
// 	{ judet: 'Constanta', nume: 'Cernavoda' },
// 	{ judet: 'Constanta', nume: 'Mangalia' },
// 	{ judet: 'Constanta', nume: 'Medgidia' },
// 	{ judet: 'Constanta', nume: 'Navodari' },
// 	{ judet: 'Constanta', nume: 'Ovidiu' },
// 	{ judet: 'Constanta', nume: 'Cumpana' },
// 	{ judet: 'Constanta', nume: 'Valu lui Traian' },
// 	{ judet: 'Constanta', nume: 'Constanta' },
// 	{ judet: 'Covasna', nume: 'Targu Secuiesc' },
// 	{ judet: 'Covasna', nume: 'Sfantu Gheorghe' },
// 	{ judet: 'Dambovita', nume: 'Gaesti' },
// 	{ judet: 'Dambovita', nume: 'Moreni' },
// 	{ judet: 'Dambovita', nume: 'Pucioasa' },
// 	{ judet: 'Dambovita', nume: 'Targoviste' },
// 	{ judet: 'Dolj', nume: 'Bailesti' },
// 	{ judet: 'Dolj', nume: 'Calafat' },
// 	{ judet: 'Dolj', nume: 'Filiasi' },
// 	{ judet: 'Dolj', nume: 'Dabuleni' },
// 	{ judet: 'Dolj', nume: 'Craiova' },
// 	{ judet: 'Galati', nume: 'Tecuci' },
// 	{ judet: 'Galati', nume: 'Matca' },
// 	{ judet: 'Galati', nume: 'Pechea' },
// 	{ judet: 'Galati', nume: 'Galati' },
// 	{ judet: 'Giurgiu', nume: 'Giurgiu' },
// 	{ judet: 'Gorj', nume: 'Motru' },
// 	{ judet: 'Gorj', nume: 'Rovinari' },
// 	{ judet: 'Gorj', nume: 'Targu Jiu' },
// 	{ judet: 'Harghita', nume: 'Gheorgheni' },
// 	{ judet: 'Harghita', nume: 'Odorheiu Secuiesc' },
// 	{ judet: 'Harghita', nume: 'Miercurea-Ciuc' },
// 	{ judet: 'Hunedoara', nume: 'Brad' },
// 	{ judet: 'Hunedoara', nume: 'Lupeni' },
// 	{ judet: 'Hunedoara', nume: 'Petrila' },
// 	{ judet: 'Hunedoara', nume: 'Simeria' },
// 	{ judet: 'Hunedoara', nume: 'Vulcan' },
// 	{ judet: 'Hunedoara', nume: 'Dragu-Brad' },
// 	{ judet: 'Hunedoara', nume: 'Deva' },
// 	{ judet: 'Hunedoara', nume: 'Hunedoara' },
// 	{ judet: 'Hunedoara', nume: 'Petrosani' },
// 	{ judet: 'Ialomita', nume: 'Fetesti-Gara' },
// 	{ judet: 'Ialomita', nume: 'Tandarei' },
// 	{ judet: 'Ialomita', nume: 'Urziceni' },
// 	{ judet: 'Ialomita', nume: 'Slobozia' },
// 	{ judet: 'Iasi', nume: 'Pascani' },
// 	{ judet: 'Iasi', nume: 'Targu Frumos' },
// 	{ judet: 'Iasi', nume: 'Iasi' },
// 	{ judet: 'Ilfov', nume: 'Buftea' },
// 	{ judet: 'Ilfov', nume: 'Otopeni' },
// 	{ judet: 'Ilfov', nume: 'Bragadiru' },
// 	{ judet: 'Ilfov', nume: 'Chitila' },
// 	{ judet: 'Ilfov', nume: 'Jilava' },
// 	{ judet: 'Ilfov', nume: 'Pantelimon' },
// 	{ judet: 'Ilfov', nume: 'Popesti-Leordeni' },
// 	{ judet: 'Ilfov', nume: 'Voluntari' },
// 	{ judet: 'Ilfov', nume: 'Pipera (Voluntari)' },
// 	{ judet: 'Maramures', nume: 'Baia Sprie' },
// 	{ judet: 'Maramures', nume: 'Borsa' },
// 	{ judet: 'Maramures', nume: 'Sighetu Marmatiei' },
// 	{ judet: 'Maramures', nume: 'Viseu de Sus' },
// 	{ judet: 'Maramures', nume: 'Poienile de sub Munte' },
// 	{ judet: 'Maramures', nume: 'Baia Mare' },
// 	{ judet: 'Mehedinti', nume: 'Orsova' },
// 	{ judet: 'Mehedinti', nume: 'Drobeta-Turnu Severin' },
// 	{ judet: 'Mures', nume: 'Ludus' },
// 	{ judet: 'Mures', nume: 'Reghin' },
// 	{ judet: 'Mures', nume: 'Sighisoara' },
// 	{ judet: 'Mures', nume: 'Tarnaveni' },
// 	{ judet: 'Mures', nume: 'Targu Mures' },
// 	{ judet: 'Neamt', nume: 'Targu Neamt' },
// 	{ judet: 'Neamt', nume: 'Piatra-Neamt' },
// 	{ judet: 'Neamt', nume: 'Roman' },
// 	{ judet: 'Olt', nume: 'Bals' },
// 	{ judet: 'Olt', nume: 'Caracal' },
// 	{ judet: 'Olt', nume: 'Corabia' },
// 	{ judet: 'Olt', nume: 'Slatina' },
// 	{ judet: 'Prahova', nume: 'Baicoi' },
// 	{ judet: 'Prahova', nume: 'Boldesti-Scaeni' },
// 	{ judet: 'Prahova', nume: 'Campina' },
// 	{ judet: 'Prahova', nume: 'Mizil' },
// 	{ judet: 'Prahova', nume: 'Sinaia' },
// 	{ judet: 'Prahova', nume: 'Valenii de Munte' },
// 	{ judet: 'Prahova', nume: 'Ploiesti' },
// 	{ judet: 'Salaj', nume: 'Simleu Silvaniei' },
// 	{ judet: 'Salaj', nume: 'Zalau' },
// 	{ judet: 'Satu Mare', nume: 'Carei' },
// 	{ judet: 'Satu Mare', nume: 'Negresti-Oas' },
// 	{ judet: 'Satu Mare', nume: 'Satu Mare' },
// 	{ judet: 'Sibiu', nume: 'Cisnadie' },
// 	{ judet: 'Sibiu', nume: 'Medias' },
// 	{ judet: 'Sibiu', nume: 'Sibiu' },
// 	{ judet: 'Suceava', nume: 'Campulung Moldovenesc' },
// 	{ judet: 'Suceava', nume: 'Falticeni' },
// 	{ judet: 'Suceava', nume: 'Gura Humorului' },
// 	{ judet: 'Suceava', nume: 'Radauti' },
// 	{ judet: 'Suceava', nume: 'Vatra Dornei' },
// 	{ judet: 'Suceava', nume: 'Vicovu de Sus' },
// 	{ judet: 'Suceava', nume: 'Suceava' },
// 	{ judet: 'Teleorman', nume: 'Rosiori de Vede' },
// 	{ judet: 'Teleorman', nume: 'Turnu Magurele' },
// 	{ judet: 'Teleorman', nume: 'Videle' },
// 	{ judet: 'Teleorman', nume: 'Zimnicea' },
// 	{ judet: 'Teleorman', nume: 'Alexandria' },
// 	{ judet: 'Timis', nume: 'Jimbolia' },
// 	{ judet: 'Timis', nume: 'Lugoj' },
// 	{ judet: 'Timis', nume: 'Sannicolau Mare' },
// 	{ judet: 'Timis', nume: 'Timisoara' },
// 	{ judet: 'Tulcea', nume: 'Tulcea' },
// 	{ judet: 'Valcea', nume: 'Dragasani' },
// 	{ judet: 'Valcea', nume: 'Valea Caselor (Dragasani)' },
// 	{ judet: 'Valcea', nume: 'Ramnicu Valcea' },
// 	{ judet: 'Vaslui', nume: 'Husi' },
// 	{ judet: 'Vaslui', nume: 'Barlad' },
// 	{ judet: 'Vaslui', nume: 'Vaslui' },
// 	{ judet: 'Vrancea', nume: 'Adjud' },
// 	{ judet: 'Vrancea', nume: 'Focsani' }
// ]

const cities = [
	'Adjud',
	'Aiud',
	'Alba Iulia',
	'Alexandria',
	'Arad',
	'Bacau',
	'Baia Mare',
	'Baia Sprie',
	'Baicoi',
	'Bailesti',
	'Bals',
	'Barlad',
	'Beius',
	'Bistrita',
	'Blaj',
	'Bocsa',
	'Boldesti-Scaeni',
	'Borsa',
	'Botosani',
	'Brad',
	'Bragadiru',
	'Braila',
	'Brasov',
	'Bucuresti',
	'Bucuresti S1',
	'Bucuresti S2',
	'Bucuresti S3',
	'Bucuresti S4',
	'Bucuresti S5',
	'Bucuresti S6',
	'Buftea',
	'Buhusi',
	'Buzau',
	'Calafat',
	'Calarasi',
	'Campia Turzii',
	'Campina',
	'Campulung',
	'Campulung Moldovenesc',
	'Caracal',
	'Caransebes',
	'Carei',
	'Cernavoda',
	'Chitila',
	'Cisnadie',
	'Cluj-Napoca',
	'Codlea',
	'Comanesti',
	'Constanta',
	'Corabia',
	'Craiova',
	'Cugir',
	'Cumpana',
	'Curtea de Arges',
	'Dabuleni',
	'Dej',
	'Deva',
	'Dorohoi',
	'Dragasani',
	'Dragu-Brad',
	'Drobeta-Turnu Severin',
	'Fagaras',
	'Falticeni',
	'Fetesti-Gara',
	'Filiasi',
	'Floresti',
	'Focsani',
	'Gaesti',
	'Galati',
	'Gheorgheni',
	'Gherla',
	'Giurgiu',
	'Gura Humorului',
	'Hunedoara',
	'Husi',
	'Iasi',
	'Jilava',
	'Jimbolia',
	'Ludus',
	'Lugoj',
	'Lupeni',
	'Mangalia',
	'Marghita',
	'Matca',
	'Medgidia',
	'Medias',
	'Miercurea-Ciuc',
	'Mioveni',
	'Mizil',
	'Moinesti',
	'Moreni',
	'Motru',
	'Navodari',
	'Negresti-Oas',
	'Odorheiu Secuiesc',
	'Oltenita',
	'Onesti',
	'Oradea',
	'Orsova',
	'Otopeni',
	'Ovidiu',
	'Pantelimon',
	'Pascani',
	'Pechea',
	'Pecica',
	'Petrila',
	'Petrosani',
	'Piatra-Neamt',
	'Pipera (Voluntari)',
	'Pitesti',
	'Ploiesti',
	'Poienile de sub Munte',
	'Popesti-Leordeni',
	'Pucioasa',
	'Radauti',
	'Ramnicu Sarat',
	'Ramnicu Valcea',
	'Rasnov',
	'Rasnov Romacril',
	'Reghin',
	'Resita',
	'Roman',
	'Rosiori de Vede',
	'Rovinari',
	'Sacele',
	'Salonta',
	'Sannicolau Mare',
	'Santana',
	'Satu Mare',
	'Sebes',
	'Sfantu Gheorghe',
	'Sibiu',
	'Sighetu Marmatiei',
	'Sighisoara',
	'Simeria',
	'Simleu Silvaniei',
	'Sinaia',
	'Slatina',
	'Slobozia',
	'Suceava',
	'Tandarei',
	'Targoviste',
	'Targu Frumos',
	'Targu Jiu',
	'Targu Mures',
	'Targu Neamt',
	'Targu Secuiesc',
	'Tarnaveni',
	'Tecuci',
	'Timisoara',
	'Tulcea',
	'Turda',
	'Turnu Magurele',
	'Urziceni',
	'Valea Caselor (Dragasani)',
	'Valenii de Munte',
	'Valu lui Traian',
	'Vaslui',
	'Vatra Dornei',
	'Vicovu de Sus',
	'Videle',
	'Viseu de Sus',
	'Voluntari',
	'Vulcan',
	'Zalau',
	'Zarnesti',
	'Zimnicea'
]

export default cities
