export const BGG_COLLECTION_LIST_REQUEST = 'BGG_COLLECTION_LIST_REQUEST'
export const BGG_COLLECTION_LIST_SUCCESS = 'BGG_COLLECTION_LIST_SUCCESS'
export const BGG_COLLECTION_LIST_FAIL = 'BGG_COLLECTION_LIST_FAIL'
export const BGG_COLLECTION_LIST_RESET = 'BGG_COLLECTION_LIST_RESET'

export const DB_COLLECTION_LIST_REQUEST = 'DB_COLLECTION_LIST_REQUEST'
export const DB_COLLECTION_LIST_SUCCESS = 'DB_COLLECTION_LIST_SUCCESS'
export const DB_COLLECTION_LIST_FAIL = 'DB_COLLECTION_LIST_FAIL'

export const WISHLIST_LIST_REQUEST = 'WISHLIST_LIST_REQUEST'
export const WISHLIST_LIST_SUCCESS = 'WISHLIST_LIST_SUCCESS'
export const WISHLIST_LIST_FAIL = 'WISHLIST_LIST_FAIL'
