export const COLLECTION_LIST_BGG_REQUEST = 'COLLECTION_LIST_BGG_REQUEST'
export const COLLECTION_LIST_BGG_SUCCESS = 'COLLECTION_LIST_BGG_SUCCESS'
export const COLLECTION_LIST_BGG_FAIL = 'COLLECTION_LIST_BGG_FAIL'
export const COLLECTION_LIST_BGG_RESET = 'COLLECTION_LIST_BGG_RESET'

export const COLLECTION_LIST_DB_REQUEST = 'COLLECTION_LIST_DB_REQUEST'
export const COLLECTION_LIST_DB_SUCCESS = 'COLLECTION_LIST_DB_SUCCESS'
export const COLLECTION_LIST_DB_FAIL = 'COLLECTION_LIST_DB_FAIL'
