export const BGG_GAMES_DETAILS_REQUEST = 'BGG_GAMES_DETAILS_REQUEST'
export const BGG_GAMES_DETAILS_SUCCESS = 'BGG_GAMES_DETAILS_SUCCESS'
export const BGG_GAMES_DETAILS_FAIL = 'BGG_GAMES_DETAILS_FAIL'
export const BGG_GAMES_DETAILS_RESET = 'BGG_GAMES_DETAILS_RESET'

export const BGG_GAMES_SEARCH_REQUEST = 'BGG_GAMES_SEARCH_REQUEST'
export const BGG_GAMES_SEARCH_SUCCESS = 'BGG_GAMES_SEARCH_SUCCESS'
export const BGG_GAMES_SEARCH_FAIL = 'BGG_GAMES_SEARCH_FAIL'
export const BGG_GAMES_SEARCH_RESET = 'BGG_GAMES_SEARCH_RESET'

export const SALE_LIST_ADD = 'SALE_LIST_ADD_SUCCESS'
export const SALE_LIST_REMOVE = 'SALE_LIST_REMOVE_SUCCESS'
export const SALE_LIST_RESET = 'SALE_LIST_RESET'

export const SELL_GAMES_REQUEST = 'SELL_GAMES_REQUEST'
export const SELL_GAMES_SUCCESS = 'SELL_GAMES_SUCCESS'
export const SELL_GAMES_FAIL = 'SELL_GAMES_FAIL'

export const TRADE_GAMES_REQUEST = 'TRADE_GAMES_REQUEST'
export const TRADE_GAMES_SUCCESS = 'TRADE_GAMES_SUCCESS'
export const TRADE_GAMES_FAIL = 'TRADE_GAMES_FAIL'

export const GAMES_INDEX_REQUEST = 'GAMES_INDEX_REQUEST'
export const GAMES_INDEX_SUCCESS = 'GAMES_INDEX_SUCCESS'
export const GAMES_INDEX_FAIL = 'GAMES_INDEX_FAIL'
export const GAMES_INDEX_RESET = 'GAMES_INDEX_RESET'

export const FOR_SALE_SINGLE_GAME_REQUEST = 'FOR_SALE_SINGLE_GAME_REQUEST'
export const FOR_SALE_SINGLE_GAME_SUCCESS = 'FOR_SALE_SINGLE_GAME_SUCCESS'
export const FOR_SALE_SINGLE_GAME_FAIL = 'FOR_SALE_SINGLE_GAME_FAIL'
export const FOR_SALE_SINGLE_GAME_RESET = 'FOR_SALE_SINGLE_GAME_RESET'

export const SAVE_GAME_SWITCH_REQUEST = 'SAVE_GAME_SWITCH_REQUEST'
export const SAVE_GAME_SWITCH_SUCCESS = 'SAVE_GAME_SWITCH_SUCCESS'
export const SAVE_GAME_SWITCH_FAIL = 'SAVE_GAME_SWITCH_FAIL'

export const SAVED_GAMES_REQUEST = 'SAVED_GAMES_REQUEST'
export const SAVED_GAMES_SUCCESS = 'SAVED_GAMES_SUCCESS'
export const SAVED_GAMES_FAIL = 'SAVED_GAMES_FAIL'
export const SAVED_GAMES_RESET = 'SAVED_GAMES_RESET'

export const SAVED_GAMES_SINGLE_REQUEST = 'SAVED_GAMES_SINGLE_REQUEST'
export const SAVED_GAMES_SINGLE_SUCCESS = 'SAVED_GAMES_SINGLE_SUCCESS'
export const SAVED_GAMES_SINGLE_FAIL = 'SAVED_GAMES_SINGLE_FAIL'

export const USER_ACTIVE_GAMES_REQUEST = 'USER_ACTIVE_GAMES_REQUEST'
export const USER_ACTIVE_GAMES_SUCCESS = 'USER_ACTIVE_GAMES_SUCCESS'
export const USER_ACTIVE_GAMES_FAIL = 'USER_ACTIVE_GAMES_FAIL'

export const GAME_DELETE_REQUEST = 'GAME_DELETE_REQUEST'
export const GAME_DELETE_SUCCESS = 'GAME_DELETE_SUCCESS'
export const GAME_DELETE_FAIL = 'GAME_DELETE_FAIL'

export const GAME_REACTIVATE_REQUEST = 'GAME_REACTIVATE_REQUEST'
export const GAME_REACTIVATE_SUCCESS = 'GAME_REACTIVATE_SUCCESS'
export const GAME_REACTIVATE_FAIL = 'GAME_REACTIVATE_FAIL'

export const saleListLimit = 6
