export const DB_COLLECTION_LIST_REQUEST = 'DB_COLLECTION_LIST_REQUEST'
export const DB_COLLECTION_LIST_SUCCESS = 'DB_COLLECTION_LIST_SUCCESS'
export const DB_COLLECTION_LIST_FAIL = 'DB_COLLECTION_LIST_FAIL'
