export const BGG_GAMES_DETAILS_REQUEST = 'BGG_GAMES_DETAILS_REQUEST'
export const BGG_GAMES_DETAILS_SUCCESS = 'BGG_GAMES_DETAILS_SUCCESS'
export const BGG_GAMES_DETAILS_FAIL = 'BGG_GAMES_DETAILS_FAIL'

export const SALE_LIST_ADD = 'SALE_LIST_ADD_SUCCESS'
export const SALE_LIST_REMOVE = 'SALE_LIST_REMOVE_SUCCESS'
export const SALE_LIST_RESET = 'SALE_LIST_RESET'
