export const HISTORY_ADD_REQUEST = 'HISTORY_ADD_REQUEST'
export const HISTORY_ADD_SUCCESS = 'HISTORY_ADD_SUCCESS'
export const HISTORY_ADD_FAIL = 'HISTORY_ADD_FAIL'
export const HISTORY_ADD_RESET = 'HISTORY_ADD_RESET'

export const HISTORY_SOLD_LIST_REQUEST = 'HISTORY_SOLD_LIST_REQUEST'
export const HISTORY_SOLD_LIST_SUCCESS = 'HISTORY_SOLD_LIST_SUCCESS'
export const HISTORY_SOLD_LIST_FAIL = 'HISTORY_SOLD_LIST_FAIL'

export const HISTORY_TRADED_LIST_REQUEST = 'HISTORY_TRADED_LIST_REQUEST'
export const HISTORY_TRADED_LIST_SUCCESS = 'HISTORY_TRADED_LIST_SUCCESS'
export const HISTORY_TRADED_LIST_FAIL = 'HISTORY_TRADED_LIST_FAIL'
