export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'
export const SEND_MESSAGE_RESET = 'SEND_MESSAGE_RESET'

export const GET_RECEIVED_MESSAGES_REQUEST = 'GET_RECEIVED_MESSAGES_REQUEST'
export const GET_RECEIVED_MESSAGES_SUCCESS = 'GET_RECEIVED_MESSAGES_SUCCESS'
export const GET_RECEIVED_MESSAGES_FAIL = 'GET_RECEIVED_MESSAGES_FAIL'

export const GET_SENT_MESSAGES_REQUEST = 'GET_SENT_MESSAGES_REQUEST'
export const GET_SENT_MESSAGES_SUCCESS = 'GET_SENT_MESSAGES_SUCCESS'
export const GET_SENT_MESSAGES_FAIL = 'GET_SENT_MESSAGES_FAIL'

export const DELETE_MESSAGES_REQUEST = 'DELETE_MESSAGES_REQUEST'
export const DELETE_MESSAGES_SUCCESS = 'DELETE_MESSAGES_SUCCESS'
export const DELETE_MESSAGES_FAIL = 'DELETE_MESSAGES_FAIL'

export const GET_NEW_MESSAGES_COUNT_REQUEST = 'GET_NEW_MESSAGES_COUNT_REQUEST'
export const GET_NEW_MESSAGES_COUNT_SUCCESS = 'GET_NEW_MESSAGES_COUNT_SUCCESS'
export const GET_NEW_MESSAGES_COUNT_FAIL = 'GET_NEW_MESSAGES_COUNT_FAIL'

export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS'
export const UPDATE_MESSAGE_FAIL = 'UPDATE_MESSAGE_FAIL'
